---
title: "R Translation Teams Dashbaord"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    favicon:
    includes:
      in_header: "../fragments/ganalytics.html"
      after_body: "../fragments/afterInit.html"
    css: ["../fragments/custom.css", "../css/custom.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(reactable)
source("../translation_teams/lang_maintainer.R")
```

Sidebar {.sidebar data-width=200}
=====================================

```{r, echo=FALSE, results='asis'}
htmltools::includeHTML('../fragments/sidebar.html')
```

Translation Teams
=====================================

Row {data-height=450}
-----------------------------------------------------------------------

### R Translation Teams | <small> Contact Details </small>

```{r}
translation_teams %>%
  reactable(
    .,
    pagination = TRUE,
    showPageSizeOptions = TRUE,
    highlight = TRUE,
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
      Language = colDef(
        name = "Translation Languages",
        filterable = TRUE,
      ),
      Members = colDef(
        name = "R-Core Lead Maintainers",
        filterable = TRUE,
      ),
      Contact = colDef(
        name = "Email Contacts",
        filterable = TRUE,
      )),
    compact = TRUE,
    bordered = TRUE,
    class = "categories-tbl"
  )
```


```{js}
```
