name: Slack refresh

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 5'
  push:
    branches:
      - main
    paths:
      - 'weblate/Slack/Weblate_Slack.R'
      - '.github/workflows/Slack.yml'
jobs:
  Running_R_scripts:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: weblate/Slack
    steps:
    - name: checkout_repo
      uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::dplyr
          any::slackr
          any::httr
          any::jsonlite
          any::knitr
          any::stringr
          any::readr
    - name: Run R scripts
      env:
        WEBLATE_TOKEN: ${{ secrets.WEBLATE_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: | 
        Rscript "Weblate_Slack.R"
