name: Weblate Library Statistics Refresh

on:
  workflow_dispatch:
  
  push:
    branches:
      - dev
    paths:
      - 'R/'
      - '.github/workflows/weblate_libraries.yml'
jobs:
  Running_R_scripts:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: R/
    steps:
    - name: checkout_repo
      uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::httr
          any::jsonlite

    - name: Run R scripts
      env: 
        WEBLATE_TOKEN: ${{ secrets.WEBLATE_TOKEN }}
      run: | 
        Rscript "library_language_statistics.R"
      
    - name: Commit and Push Any Changes
      run: |
        git pull
        git add *.csv
        if ! git diff-index --quiet HEAD; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated weblate library csv"
          git push
        fi
